// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/inventory/inventory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definisikan Pesan (Bentuk datanya gimana?)
type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID Produk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_proto_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetStockResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetStockResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_proto_inventory_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/inventory/inventory.proto\x12\tinventory\"!\n" +
	"\x0fGetStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"L\n" +
	"\x10GetStockResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock2W\n" +
	"\x10InventoryService\x12C\n" +
	"\bGetStock\x12\x1a.inventory.GetStockRequest\x1a\x1b.inventory.GetStockResponseB\x1cZ\x1aphase3-api-architecture/pbb\x06proto3"

var (
	file_proto_inventory_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_inventory_proto_rawDescData []byte
)

func file_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_inventory_proto_rawDesc), len(file_proto_inventory_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_inventory_proto_rawDescData
}

var file_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_inventory_inventory_proto_goTypes = []any{
	(*GetStockRequest)(nil),  // 0: inventory.GetStockRequest
	(*GetStockResponse)(nil), // 1: inventory.GetStockResponse
}
var file_proto_inventory_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.GetStock:input_type -> inventory.GetStockRequest
	1, // 1: inventory.InventoryService.GetStock:output_type -> inventory.GetStockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_inventory_proto_init() }
func file_proto_inventory_inventory_proto_init() {
	if File_proto_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_inventory_proto_rawDesc), len(file_proto_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_inventory_proto = out.File
	file_proto_inventory_inventory_proto_goTypes = nil
	file_proto_inventory_inventory_proto_depIdxs = nil
}
